title: WINDOWS-AHK
description: >
  A simple and intuitive AutoHotKey script designed to enhance Windows shortcuts and improve your workflow.

url: "https://windows-ahk.bibeka.com.np"

# Use default minimal theme
theme: minima

github_repo_url: "https://github.com/arlbibek/windows-ahk"
